### ISSUE TITLE
An error in the use of dropseqRunner

### ISSUE THREAD

**Issue by lyxwyc** [aselewa/dropseqRunner#3]
In the Run the pipeline step, I followed the instructions, but an error occurred, as shown in the attached picture.
Specifically like this：
Running snakemake directly on this node. This may not finish because alignment requires >30GB of RAM.
{'SRR6075354', 'SRR6075354_0'}
Building DAG of jobs...
MissingInputException in line 113 of /home/liyx/app/dropseqRunner/droprunner/Snakefile_drop.smk:
Missing input files for rule make_report:
/home/liyx/data/lizard/output/qc_data/SRR6075354_0_RNAmetrics.picard.txt

I did not find the way to generate file {sample}_RNAmetrics.picard.txt in all the scripts given. And I don't know how to solve this error. 
![error](https://user-images.githubusercontent.com/69193460/91813153-cbe6b280-ec64-11ea-8947-a1c297147acc.jpg)
I really need your help now and hope to get your reply soon. Thank you！

**Comment by lyxwyc** [comment]
![error](https://user-images.githubusercontent.com/69193460/91813525-6e9f3100-ec65-11ea-84ce-52ffcead1b0d.jpg)

**Comment by aselewa** [comment]
fixed. closing now
